version: "3.8"
services:
    nodeserver:
        image: parthvadhwana/node
        build:
            context: ./
            
        ports:
            - "3000:3000"
    nginx:
        image: parthvadhwana/deskshare-nginx
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"